#!/usr/bin/perl -n
# numbered_commands_to_deps - output dependencies between file args and command numbers, for tsort
use strict;
use warnings;
chomp;
my ($n, @args) = split /\t/, $_;
for my $arg (@args) {
	if ($arg =~ s/^<|<$//) {
		print "$arg\t$n\n";
	} elsif ($arg =~ s/^>|>$//) {
		print "$n\t$arg\n";
	}
}
