#!/bin/bash -eu

# setup the allemande ports for a user
# usage: allemande-user-add [user [module ...]]

user=${1:-$USER}
if [ "$#" -gt 0 ]; then shift; fi
modules=(${@:-$ALLEMANDE_MODULES})
ports="$ALLEMANDE_PORTS"

if [ `id -u` != 0 ]; then
	exec sudo -E "$0" "$user" "${modules[@]}"
	exit $?
fi

for module in "${modules[@]}"; do
	module_dir="$ports/$module"
	user_dir="$module_dir/$user"

	mkdir -p "$module_dir"
	chown $ALLEMANDE_USER:$ALLEMANDE_USER "$module_dir"

	umask 007
	mkdir -p "$user_dir"
	for box in $ALLEMANDE_BOXES; do
		mkdir -p "$user_dir/$box"
	done
	chown -R $user:$ALLEMANDE_USER "$user_dir"

	chmod -R g+s,ug-x+X "$user_dir"   # the 2 is for setgid (group sticky bit)
done
