#!/bin/bash -eu
set -o pipefail

cd "$ALLEMANDE_HOME"

git checkout main

git pull sam@ucm.dev:allemande
git pull sam@pi.ucm.dev:allemande
git push sam@ucm.dev:allemande
git push sam@pi.ucm.dev:allemande

git-add-commit

git push; git pull

for branch in allemande barbarella; do
	git checkout $branch
	git pull
	git merge --no-edit main
	git push ; git pull
done

git checkout main
