#!/bin/bash -eu
set -o pipefail

git checkout main

git-add-commit

#arcs
git push; git pull

for branch in allemande barbarella; do
	git checkout $branch
	git pull
	git merge --no-edit main
	git push ; git pull
done

git checkout main

if [ -n "`git-ls-untracked`" -o -n "`git-ls-unstaged`" ]; then
	echo >&2 "not running arcs because of untracked or unstaged files"
else
	arcs
fi
