#!/bin/bash -eu
set -o pipefail

git checkout main

git-confirm-add-commit

arcs
git push; git pull

for branch in allemande barbarella; do
	git checkout $branch
	git merge --no-edit main
	git push; git pull
done

git checkout main
