#!/bin/bash -eu
set -o pipefail

PULL="git pull --commit --no-edit"
MERGE="git merge --no-edit"
PUSH="git push"
CO="git checkout"

cd "$ALLEMANDE_HOME"

$CO main

$PULL sam@ucm.dev:allemande
$PULL sam@pi.ucm.dev:allemande
$PUSH sam@ucm.dev:allemande main
$PUSH sam@pi.ucm.dev:allemande main

llm-git-commit -n

$PULL $ALLEMANDE_GITHUB main
$PUSH $ALLEMANDE_GITHUB main

$CO allemande
$PULL sam@ucm.dev:allemande allemande
$PULL sam@pi.ucm.dev:allemande allemande
$PUSH sam@ucm.dev:allemande allemande
$PUSH sam@pi.ucm.dev:allemande allemande
$PULL $ALLEMANDE_GITHUB allemande
$MERGE main
$PUSH $ALLEMANDE_GITHUB allemande
$PULL $ALLEMANDE_GITHUB allemande

$CO barbarella
$PULL sam@ucm.dev:barbarella barbarella
$PULL sam@pi.ucm.dev:barbarella barbarella
$PUSH sam@ucm.dev:allemande allemande
$PUSH sam@pi.ucm.dev:allemande allemande
$PULL $BARBARELLA_GITHUB barbarella
$MERGE main
$PUSH $BARBARELLA_GITHUB barbarella
$PULL $BARBARELLA_GITHUB barbarella

$CO main
