#!/bin/bash -eu
# web-install: set permissions for the web app and install nginx config

. get_root

mode() {
	mode=$1 ; shift
	chown $SUDO_USER:www-data "$@"
	chmod $mode "$@"
}

rm -f /var/www/allemande
ln -s "$ALLEMANDE_HOME/site" /var/www/allemande

cd "$ALLEMANDE_HOME/js"
if [ ! -e js/mousetrap ]; then
	git clone https://github.com/ccampbell/mousetrap js/mousetrap
fi

cd "$ALLEMANDE_HOME/webchat"

mkdir -p files
mode 771 rooms files
mode 660 rooms/*.bb rooms/*.html
mode 440 rooms/-.bb rooms/-.html
if [ ! -e .htpasswd ]; then
	touch .htpasswd
fi
mode 640 .htpasswd static/logout/.htpasswd

rm -f /var/www/allychat
ln -s $PWD /var/www/allychat

cd "$ALLEMANDE_HOME/adm/nginx"
for site in *; do
	ln -sf "$PWD/$site" /etc/nginx/sites-available/
	ln -sf "../sites-available/$site" /etc/nginx/sites-enabled/
done


# build pro


cd "$ALLEMANDE_HOME/pro"
ln -s $PWD /var/www/allychat-pro
npm run build
cd build
ln -s ../package*.json ./
npm ci --omit dev


systemctl restart nginx
