#!/bin/bash -eu
# webui-uninstall: uninstall nginx config

. get_root

cd "$ALLEMANDE_HOME/webui/nginx"

for site in *; do
	rm -f "/etc/nginx/sites-enabled/$site"
	rm -f "/etc/nginx/sites-available/$site"
done

systemctl restart nginx
