#!/bin/bash -eu
# improve:	improve a program using AI
# usage: improve prog.py "instructions to improve it" [optional reference files]

m=c

. opts

prog=$1
if [ ! -e "$prog" ]; then
	prog=`wich $prog`
fi
shift

dir=`dirname "$prog"`
base=`basename "$prog"`

(
	cd "$dir"
	git add "$base"
	cp -a "$base" "$base~"
)

prompt="Please improve $base: $1"
shift

cat_named.py -p -b "$prog" "$@" | process -m="$m" "$prompt" | markdown_code.py -c '#' > "$prog~"

(
	cd "$dir"
	swapfiles "$base" "$base~"
	vimdiff "$base" "$base~"
	mr "$base~"
)
