#!/bin/bash -eu
# prog-sh:	basic program generator for shell scripts

m=c

. opts

name=${1%.sh}.sh
shift
if [ "$#" = 0 ]; then
	echo >&2 usage: prog name "about the program"
	exit 1
fi
cat-named "`wich hello.sh`" |
	process -m="$m" "Please write a bash program in the style of hello.sh: $*" |
	markdown_code.py -c '#' |
	tee "$name"
cx "$name"
wc "$name"
