#!/bin/bash -eu
# prog:	basic program generator

m=c

. opts

name=${1%.py}.py
shift
if [ "$#" = 0 ]; then
	echo >&2 usage: prog name "about the program"
	exit 1
fi
cat-named "`wich hello.py`" |
	process -m="$m" "Please write a Python program in the style of hello.py: $*" |
	markdown_code.py -c '#' |
	tee "$name"
cx "$name"
wc "$name"
