#!/bin/bash -eu
# llm-last:	show the most recent llm generation from ~/llm.log

f=0	# output filenames, not content
m=	# view markdown in Chrome with Markdown Viewer
. opts

if [ "$m" = 1 ]; then
	view=chrome
else
	view=cat
fi

cd ~/llm.log

for i in "${@:-1}"; do
	case "$f" in
	0)
		ls1 -n="$i" | xa "$view"
		echo
		echo
		;;
	1)
		ls1 -n="$i"
		;;
	esac
done
