#!/bin/bash -eu
m=$ALLEMANDE_LLM_DEFAULT
I=	# don't fix indentation
. opts
process_main() {
	llm process -m "$m" "${@:-""}" | rstrip
}
if [ "$I" ]; then
	process_main "$@"
else
	input=$(cat)
	indent=$(printf "%s\n" "$input" | indenter --detect)
	printf "%s\n" "$input" | process_main "$@" | indenter --apply "$indent"
fi
