CC=gcc
CFLAGS=-Wall -Wextra -pedantic -std=gnu11
LDLIBS=-lGL -lGLU -lX11 -lm

disabled:
	@echo >&2 "build disabled, run make glxgears if you want to build it!"

glxgears: glxgears.c

clean:
	rm -f glxgears
