#!/bin/bash -eu
# whisp: a bash wrapper for whisper and whisper.cpp via whisper-cpp.sh

# TODO 1. use Allemande ports API if available
# TODO 2. use Python whisper 
# TODO 3. use whisper-cpp.sh
# TODO 4. use whisper-api.py to access whisper through OpenAI APIs if an API key is defined

c=

. opts

cpu=$c

if command -v whisper &> /dev/null && [ "$c" != 1 ]; then
	v whisper "$@" || v whisper-cpp.sh "$@"
else
	v whisper-cpp.sh "$@"
fi
