#!/bin/bash -eua
# landmarks_runner:	run giles on a list of landmarks

# TODO when ^C kill all child processes
# also for giles and alfred

PROG_DIR=$(dirname "$(readlink -f "$0")")
PATH=$PATH:$PROG_DIR

. wordpress-env.sh

region=", Bass Coast, Victoria"
PARALLEL_MAX=6

. opts

run_giles_for_landmarks() {
	printf "\n\n----------------------------------------\n\n"
	printf "*** $name ***\n\n"
	mkdir -p "$name"
	for mission in mission.*.in.txt; do
		if [ ! -f "$mission" ]; then
			continue
		fi
		cp "$mission" "$name"
	done
	query="$name$region"
	(
		cd "$name"
		giles query="$query" HTML_DUMP_FILTER="landmarks_html_dump_filter" summary_prompt="Please summarize this info in detail, as relating to $query, using markdown dot-point form. Be as comprehensive and factual as possible. Please include as much factual information as possible. Cover a comprehensive scope of things to see, do, history, how to get there, what's around, and things to be careful of. Stay focused on the topic, do not gives details of other areas. Be factual."
	) 2>&1 | tee -a "$name/runner.log"
}

while read name; do
	. parallel run_giles_for_landmarks
done
wait

# ./add_all_to_wordpress
