#!/bin/bash -eua
# landmarks_runner:	run giles on a list of landmarks

. wordpress-env.sh

region=", Bass Coast, South Gippsland, Victoria"
PARALLEL_MAX=50

. opts

run_giles_for_landmarks() {
	printf "\n\n----------------------------------------\n\n"
	printf "*** $name ***\n\n"
	mkdir -p "$name"
	for mission in mission.*.in.txt; do
		if [ ! -f "$mission" ]; then
			continue
		fi
		cp "$mission" "$name"
	done
	query="$name$region"
	(
		cd "$name"
		giles query="$query"
	) 2>&1 | tee -a "$name/runner.log"
}

while read name; do
	. parallel run_giles_for_landmarks
done
wait

# ./add_all_to_wordpress
