#!/bin/bash -eua
# run_tourism:	run giles on a list of tourist traps

# TODO when ^C kill all child processes
# also for giles and alfred

PROG_DIR=$(dirname "$(readlink -f "$0")")
PATH=$PATH:$PROG_DIR

. wordpress-env.sh

region=", Bass Coast, Victoria"
PARALLEL_MAX=8

. opts

run_giles_for_tourism() {
	printf "\n\n----------------------------------------\n\n"
	printf "*** $name ***\n\n"
	mkdir -p "$name"
	for mission in tourism-missions/mission.*.in.txt; do
		if [ ! -f "$mission" ]; then
			continue
		fi
		cp "$mission" "$name"
	done
	query="$name$region"
	(
		cd "$name"
		giles query="$query" HTML_DUMP_FILTER="html_dump_filter_tourism" summary_prompt="Please summarize this info in detail, as relating to $query, using markdown dot-point form. Be as comprehensive and factual as possible. Please include as much factual information as possible. Cover a comprehensive scope of things to see, do, history, how to get there, what's around, and things to be careful of. Stay focused on the topic, do not give details of other areas. Be factual."
	) 2>&1 | tee -a "$name/run_tourism.log"
}

names=()

while read name; do
	. parallel run_giles_for_tourism
	names+=("$name")
done
wait

./add_all_to_wordpress "${names[@]}"
