#!/bin/bash -eua
# run_tourism:	run giles on a list of tourist traps

# TODO when ^C kill all child processes
# also for giles and alfred

PROG_DIR=$(dirname "$(readlink -f "$0")")
PATH=$PATH:$PROG_DIR

. wordpress-env.sh

region=", South Gippland, Victoria"
PARALLEL_MAX=8

. opts

run_giles_for_tourism() {
	local name=$1
	if [ -L "$name" ]; then
		printf "*** $name is already done ***\n\n"
		return
	fi
	printf "\n\n----------------------------------------\n\n"
	printf "*** $name ***\n\n"
	mkdir -p "$name"
	for mission in missions/tourism/mission.*.in.txt; do
		if [ ! -f "$mission" ]; then
			continue
		fi
		cp "$mission" "$name"
	done
	query="$name$region"
	(
		cd "$name"
		giles query="$query" HTML_DUMP_FILTER="html_dump_filter_tourism" SUMMARY_GUIDE="Cover a comprehensive scope of Things to See, Things to Do, History / Learning, How to Get There, What's Around, Warnings / Things to be Careful Of, Where to Stay, What's in the Area, Events, Local Groups, what to Eat and Drink, and Accessibility; and whatever else seems interesting."
	) 2>&1 | tee -a "$name/run_tourism.log"
}

names=()

while read name; do
	. parallel run_giles_for_tourism "$name"
	names+=("$name")
	sleep .$RANDOM
done
wait

./add_all_to_wordpress "${names[@]}"
