#!/bin/bash
m=
d=
. opts
if [ -n "$d" ]; then debug="tee /dev/stderr"; else debug="cat"; fi
(
	printf "%s\n\n" "user:	$1" | sed '2,$s/^/	/'
	sed 's/^/		/'
	if [ -n "$2" ]; then
		printf "\n%s\n" "$2" | sed 's/^/	/'
	fi
) | $debug | gpt -m "$m" | cut -f2 | sed 's/    /\t/g'
