#!/bin/bash -eu
# pandoc-dump:	Convert HTML to Markdown, as cleanly as possible.

c=1	# clean
m=1	# metadata

. opts

html="$1"
url="${2:-}"

clean=$c
metadata=$m

pandoc_convert() {
	pandoc --wrap=none -f html -t markdown
}

clean() {
	pandoc-dump-clean |
	single-blank-lines.pl
#	pandoc-dump-clean-2
}

show_metadata() {
	local title=`html-title < "$html"`
	printf "title: %s\n" "$title"
	if [ -n "$url" ]; then
		printf "From: %s\n" "$url"
	fi
	echo
}

prepare_input() {
#	printf "<h1>title: %s</h1>\n" "$title"
#	if [ -n "$url" ]; then
#		printf "<h2>From: %s</h2>\n" "$url"
#	fi
	cat "$html"
}

if [ "$metadata" = 1 ]; then
	show_metadata
fi

if [ "$clean" = 1 ]; then
	< "$html" pandoc-dump-clean-html | pandoc_convert | clean
else
	< "$html" prepare_input | pandoc_convert
fi
