#!/usr/bin/perl
# pandoc-dump-clean-w - clean up pandoc HTML to markdown dump, multi-line cleanup e.g. Wikipedia

use strict;
use warnings;

undef $/;

$_ = <STDIN>;

if (/<meta name="generator" content="MediaWiki/) {
#	s{<li class="interlanguage-link.*?</li>}{}g;
#	s{<a class="vector-toc-link"[^>]*>\s*<div class="vector-toc-text">\s*(.*?)</div>\s*</a>}{$1}gs;
	s{\A.*?(<div id="bodyContent)}{$1}s;
	s{<h2><span class="mw-headline" id="See_also">.*}{}s;
}

print "$_";
