#!/bin/bash -eu
# pandoc-dump:	Convert HTML to Markdown, as cleanly as possible.

c=1	# clean

. opts

html="$1"
url="${2:-}"

clean=$c
title=`html-title < "$html"`

pandoc_convert() {
	pandoc --wrap=none -f html -t markdown
}

clean() {
	pandoc-dump-clean |
	single-blank-lines.pl
}

prepare_input() {
	printf "<h1>title: %s</h1>\n" "$title"
	if [ -n "$url" ]; then
		printf "<h2>From: %s</h2>\n" "$url"
	fi
	cat "$html"
}

if [ "$clean" = 1 ]; then
	prepare_input | pandoc_convert | clean
else
	prepare_input | pandoc_convert
fi
