#!/bin/bash -eu
# Run assistant in watch mode with the experiment config,
# the -r option for raw / free-form input, and the --no-trim option
# to allow the model to predict the user.
cd "$(dirname "$(readlink -f "$0")")/.."
assistant -w . -c config/experiment.yaml -v "$@" -r --no-trim
