#!/bin/bash -eu
# add all output.md to wordpress

t=post

. opts

item_type=$t

for D; do
	D=${D%/}
	if [ ! -s "$D/output.1.md" ] || [ ! -s "$D/output.2.md" ]; then
		echo >&2 "___ SKIPPING BUILD $D"
		continue
	fi

	echo "*** PROCESSING $D"

	ln -sf "$D/output.1.md" "$D.md"
	ln -sf "$D/output.1.md" "$D.meta"
	v ./place_md_to_wordpress.py -a "$D, Bass Coast, Victoria" -t template/tourism.txt -c "$D/output.1.md" -m "$D/output.2.md" > "$D.wordpress"
#	v ./place_md_to_wordpress -a "$D, Bass Coast, Victoria" < "$D.md" > "$D.wordpress"
done

mkdir -p DONE

for D; do
	D=${D%/}
	if [ ! -s "$D/output.1.md" ] || [ ! -s "$D/output.2.md" ]; then
		echo >&2 "___ SKIPPING PUSH $D"
		continue
	fi

	echo "*** PUSHING TO WORDPRESS $D"

	wordpress_put.py --type $item_type --title "$D" "$D.wordpress"

	# move to done folder
	mv "$D" "DONE/"
done
