#!/bin/bash -eu
# add all output.md to wordpress

t=post

. opts

item_type=$t

for D; do
	D=${D%/}
	if [ ! -s "$D/output.1.md" ] || [ ! -s "$D/output.2.md" ]; then
		echo >&2 "___ SKIPPING BUILD $D"
		continue
	fi

	echo "*** PROCESSING $D"

	ln -sf "$D/output.1.md" "$D.md"
	ln -sf "$D/output.2.md" "$D.meta"
	v ./prettify.py -a "$D, Bass Coast, Victoria" -t template/tourism.txt -c "$D.md" -m "$D.meta" > "$D.wordpress"
done

mkdir -p DONE

for D; do
	D=${D%/}
	if [ ! -s "$D/output.1.md" ] || [ ! -s "$D/output.2.md" ]; then
		echo >&2 "___ SKIPPING PUSH $D"
		continue
	fi

	echo "*** PUSHING TO WORDPRESS $D"

	v ./injectify.py --auto --$item_type --title "$D" --file "$D.wordpress"

	mvlnback "$D" "DONE/"
done
