type: llm_llama
model: default
filter_out:
  - truncate_repeated_characters
context: 30
lines: 3
system_bottom_pos: 5
stop_regexs:
  - \n\t*\n\t*\n
system_top: |-
  $NAME_FULLNAME_ALIASES.
system_bottom: |-
  I am $NAME.
