#!/bin/bash -eu
# video to flashcards

url=$1
shift
cache_dir=$HOME/.cache/flash/
dir=$cache_dir${url/:\/\//\/}

# cache dir is url, with :// changed to /
# We need to sanitise the URL / cache dir.

# get canonical pathname for dir
dir=$(readlink -m "$dir")

# must be under the cache_dir
if [[ ! "$dir" =~ ^"$cache_dir" ]]; then
    echo "Invalid URL: $url" >&2
    exit 1
fi

# Create the cache dir if it doesn't exist
mkdir -p "$dir"
cd "$dir"

# The tool is a Makefile, so it will not re-run the job if it is already done.
# We can just run the makefile instead of checking if it is already cached.
if flash.make url="$url" "$@" >&2; then
    v cat post.txt
else
    # delete empty files
    status=$?
    find "$dir" -type f -size 0 | xa rm -f
    exit $status
fi
