#!/bin/bash
# mr - move to rubbish
# mr @files
# moves each of @files to ~/rubbish/${basename}_`nano=1 dt0`
if [ -z "$RUBBISH" ]; then
	M=`mntpoint "$1"`
	if [ "$M" = "$(mntpoint "$HOME")" -o "$M" = / ]; then
		RUBBISH="$HOME/.rubbish"
	else
		RUBBISH="$M/.rubbish"
	fi
fi
(umask 0700; mkdir -p "$RUBBISH"; chmod 0700 "$RUBBISH")
for A; do
	N=`basename -- "$A"`
	while true; do
		B="$RUBBISH/${N}_`nano=1 dt0`_$$"
		[ -e "$B" ] || break  # XXX not entirely secure, should use >| to creat or something?
	done
	mv -v -i -- "$A" "$B" || exit 1
	[ -n "$mr_echo" ] && echo "$DEST"
done
exit 0
