#!/bin/bash
# [image ...]
# Show the parameters of an image, generated by Stable Diffusion or similar.

single_line= s=0	# Show the parameters on a single line

eval "$(ally)"

for I; do
	info=`ii "$I"`
	echo "$info" | grep '^Steps:' |
	perl -pe 's{(TI hashes: ")(.*?)(")}{$1 . join(", ", keys %{{ map {$_ => 1} split(/, /, $2) }}) . $3}e'

	echo

	echo "$info" | grep '^ *parameters:' |
	sed 's/^ *parameters: */Parameters:\n\n/;' |
	if [ "$single_line" = 1 ]; then
		cat
	else
		split-prompt
#		sed 's/, */,\n/g' | grep -v '^,$'
	fi

	echo

	echo "Negative prompt:"
	echo
	echo "$info" | grep '^Negative prompt:' |
	sed 's/^Negative prompt: //;' |
	if [ "$single_line" = 1 ]; then
		cat
	else
		split-prompt
#		sed 's/, */,\n/g' | grep -v '^,$'
	fi

	echo
	echo
done |
highlight '<[^>]*>' red || true
