#!/bin/sh
cmd=${1#^} file=$2
case "$cmd" in
D)
	i3_popup_xterm -H -g=80x80 image_debug.sh "$file"
	;;
P)
	i3_popup_xterm -H -g=80x80 image-params "$file"
	;;
[0-9])
	dir=$cmd
	mkdir -p "$dir"
	mv -n "$file" "$dir"/
	;;
*)
	echo >&2 "Unknown command: $cmd"
	exit 1
	;;
esac
